#!/bin/bash

make
if [ $? -ne 0 ]; then
	echo "couldn't make"
	exit $?
fi

echo ""

if [[ "$1" == "test" ]]; then
	# no args
	echo "./PmergeMe"
	timeout --kill-after=1s 5s ./PmergeMe
	echo ""

	# negative value
	echo "./PmergeMe -8 4 7 2 1"
	timeout --kill-after=1s 5s ./PmergeMe -8 4 7 2 1
	echo ""
	
	# overflowed value
	echo "./PmergeMe 4294967296 4 7"
	timeout --kill-after=1s 5s ./PmergeMe 4294967296 4 7
	echo ""

	# non-digit value
	echo "./PmergeMe 8e 4 7"
	timeout --kill-after=1s 5s ./PmergeMe 8e 4 7
	echo ""

	# non-digit value
	echo "./PmergeMe 8 e 4 7"
	timeout --kill-after=1s 5s ./PmergeMe 8 e 4 7
	echo ""

	# empty string
	echo "./PmergeMe \"\""
	timeout --kill-after=1s 5s ./PmergeMe ""
	echo ""

	# space string
	echo "./PmergeMe \" \""
	timeout --kill-after=1s 5s ./PmergeMe " "
	echo ""

	# single value
	echo "./PmergeMe 6"
	timeout --kill-after=1s 5s ./PmergeMe 6
	echo ""

	# single value
	echo "./PmergeMe \"6\""
	timeout --kill-after=1s 5s ./PmergeMe "6"
	echo ""

	# two values
	echo "./PmergeMe 6 4"
	timeout --kill-after=1s 5s ./PmergeMe 6 4
	echo ""

	# two values
	echo "./PmergeMe \"6 4\""
	timeout --kill-after=1s 5s ./PmergeMe "6 4"
	echo ""

	# three values
	echo "./PmergeMe 2 6 4"
	timeout --kill-after=1s 5s ./PmergeMe 2 6 4
	echo ""

	# three values
	echo "./PmergeMe \"2 6 4\""
	timeout --kill-after=1s 5s ./PmergeMe "2 6 4"
	echo ""
	
	exit $?
fi

SIZE=$1

if [ -z $SIZE ]; then
	# timeout --kill-after=1s 5s ./PmergeMe "14 2 9 34 3 11 88 7 41 6 8 4 85"

	# if [ $? -eq 124 ]; then
	# 	echo "timed out (1)"
	# fi

	# timeout --kill-after=1s 5s ./PmergeMe "18 75 5 0 100 20 91 3 34 88 2 8 1 11 7 62 4 16 9 41 14 6 25"

	# timeout --kill-after=1s 5s ./PmergeMe 14 2 9 34 3 11 88 7 41 6 8 4 85

	# if [ $? -eq 124 ]; then
	# 	echo "timed out (1)"
	# fi

	# timeout --kill-after=1s 5s ./PmergeMe 18 75 5 0 100 20 91 3 34 88 2 8 1 11 7 62 4 16 9 41 14 6 25

	# if [ $? -eq 124 ]; then
	# 	echo "timed out (2)"
	# fi

	timeout --kill-after=1s 5s ./PmergeMe "30 49 60 1 31 29 42 46 13 8 5"

	if [ $? -eq 124 ]; then
		echo "timed out (1)"
	fi
else
	NBS=$(shuf -i 1-$SIZE | tr '\n' ' ')

	timeout --kill-after=1s 5s ./PmergeMe $NBS

	if [ $? -eq 124 ]; then
		echo "timed out (1)"
	fi
fi


